---
title: "R Notebook"
output: html_notebook
---



```{r}

set.seed(2121)

simData <- bmlm::BLch9

vars <- colnames(simData[, 3:5])

simDATA_split <- split.data.frame(simData, simData$id)

nTime <- unique(sapply(simDATA_split, nrow))

nPerson <- length(simDATA_split)

iList <- list()

for (i in 1:nPerson){
  
  jList <- list()
  
  for (j in 1:length(vars)) {
    
    perMiss <- sample(seq(.1,.4,.1),1)
    
    nMiss<- perMiss * nTime
    
    missInds <- sort(sample(1:nTime, nMiss, replace = FALSE ))
    
    tempVec <- simDATA_split[[i]][, vars[j] ] 
    
    tempVec[missInds]<- NA
    
    jList[[j]] <-  tempVec
    
  }
  
  tempDat <- do.call("cbind", jList)
  
  colnames(tempDat) <- vars
  
  tempDat <- data.frame(tempDat, ID = simDATA_split[[i]]$id, day = 1:nTime )
  
  iList[[i]]<- tempDat
  
}

simData_cmbnd <- do.call("rbind", iList)
```

```{r}
rowMiss <- apply(simData_cmbnd, 1, anyNA)

propMiss <- round(sum(rowMiss == TRUE)/ length(rowMiss), 2)

propMiss

apply(simData_cmbnd[, 1:3], 2, function(x) sum(is.na(x))/length(x))


```



```{r}

a_out <- Amelia::amelia(simData_cmbnd, cs = "ID", ts = "day" , intercs = TRUE , m = 10)

imps <- a_out$imputations

```

```{r}

bootImp <- foreach(i=1:length(imps)) %dopar% par_mlVAR00(dat = imps[[i]], scale = TRUE, variables = vars, ID = "ID", rfStructure = c("correlated", "correlated"), timeArgs = list(NULL, NULL, FALSE))

#stopCluster(cl)

```


```{r}

combined_ests <- rubin_combine(bootImp, m =length(imps))

combined_ests$temporal$t_value

combined_ests$contemporaneous_network$t_value

combined_ests$`between-subjects_network`$t_value

list(temporal = combined_ests$temporal$t_value, contemporaneous = combined_ests$contemporaneous_network$t_value, betweenSubjects = combined_ests$`between-subjects_network`$t_value)

```

```{r}
completeData <- mlVAR00(dat = simData, scale = TRUE, variables = vars, ID = "id", temporal = "correlated", contemporaneous = "correlated")

list(temporal = completeData$results$temporal$`T-value`, contemporaneous = completeData$results$contemporaneous$`T-value`, betweenSubjects = completeData$results$`between-subjects`$`T-value`)

```



```{r}
completeData_time <- mlVAR00(simData, variables = vars, ID = "id", temporal = "correlated", contemporaneous = "correlated" , scale = TRUE, timeVar = "time", timePoly = 0, timeRandom = TRUE )

list(temporal = completeData_time$results$temporal$`T-value`, contemporaneous = completeData_time$results$contemporaneous$`T-value`, betweenSubjects = completeData_time$results$`between-subjects`$`T-value`)


```

